#Actualizacion de Costos (CCB) y Tarifas
#Thu Mar 12 17:40:36 VET 2026
ccb_actual=4.255000000000001
desayuno_descripcion=Papas, no s\u00E9
desayuno_imagen=C\:\\Users\\WinterOS\\Documents\\proyecto-comedor-2-2025-grupo-12\\src\\main\\resources\\images\\menu\\platillo_0_1772028112963.jpg
desayuno_nombre=Papas
desayuno_nutricion=tampoco le s\u00E9
desayuno_precio=$ 2000
tarifa_pct_empleado=95.0
tarifa_pct_estudiante=25.0
tarifa_pct_profesor=75.0
