#Actualizacion de Costos (CCB) y Tarifas
#Thu Mar 12 17:26:18 VET 2026
almuerzo_descripcion=
almuerzo_imagen=C\:\\Users\\hanli\\Desktop\\repo-correci-n-comedor-ucv\\imagenes_menu\\platillo_0_1772028112963.jpg
almuerzo_nombre=Almuerzo
almuerzo_nutricion=
almuerzo_precio=$ 4000
ccb_actual=4.255000000000001
desayuno_descripcion=Hola no s\u00E9 esto es un test
desayuno_imagen=C\:\\Users\\WinterOS\\Documents\\repo-correci-n-comedor-ucv\\imagenes_menu\\platillo_0_1772028112963.jpg
desayuno_nombre=Papas 
desayuno_nutricion=hayaca 15%\navena 90%
desayuno_precio=$ 1000
imagen_0=C\:\\Users\\wilber_2\\Desktop\\proyecto-comedor-2-2025-grupo-12\\imagenes_menu\\platillo_0_1772029599586.jpg
nombre_0=pasta
precio_0=$36000
tarifa_pct_empleado=95.0
tarifa_pct_estudiante=25.0
tarifa_pct_profesor=75.0
